spring.application.name=sury_back

spring.datasource.url=jdbc:h2:mem:sury_db;DB_CLOSE_DELAY=-1;
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enebled=true
spring.h2.console.path=/h2-console